[package]
name = "terminal-alarm"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fon = "0.6.0"
soloud = "1.0.2"
twang = "0.9.0"
